input_data:
  version: # TF Data/Records object

build_params:
  model_name: test
  input_shape: !!python/tuple [180, 180, 3] # [rows, columns, channels]
  n_classes: 5
  n_filters: 16 
  dense_nodes: 256
  conv_dropout: 0.25 
  dense_dropout: 0.5  
  filter_size: !!python/tuple [3, 3] # [rows, columns]
  pool_size: !!python/tuple [2, 2] # [rows, columns]
  output_activation: linear

compile_params:
  loss: mean_squared_error
  optimizer: adam
  learning_rate: 0.001
  metrics: [root_mean_squared_error, mean_absolute_error]

train_params:
  batch_size: 128
  epochs: 5
  callbacks:

save_instructions:
  model_path:
  history_path: