
# Modify this file before running container and sending job

build_params:
  # Model type options:
  # default, mobilenet_v2, efficientnet_b7, efficientnet_v2l
  # vgg16, vgg19, xception, resnet50
  model_type: vgg16
  input_shape: !!python/tuple [224, 224, 3] # [rows, columns, channels]
  dense_nodes: 64
  output_activation: linear

  # Set these parameters for the default model 
  n_classes: 5
  n_filters: 32 
  conv_dropout: 0.25 
  dense_dropout: 0.5  
  filter_size: !!python/tuple [3, 3] # [rows, columns]
  pool_size: !!python/tuple [2, 2] # [rows, columns]

compile_params:
  loss: mean_squared_error
  optimizer: adam
  learning_rate: 0.001
  metrics: [rmse, mae, mse]

train_params:
  batch_size: 4
  epochs: 200
  early_stopping: True
  patience: 10
  fine_tune: True
