version: '3'
services:

  image_prep:
    build:
      context: app/src/image_prep
    volumes:
      - ./src/image_prep:/image_prep
      - ./data:/data
    environment:
      - PYTHONBREAKPOINT=0

  app:
    build:
      context: ./src/app
    ports:
      - 8000:8000